version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres 
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: 
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck: #optional
      test: ['CMD','pg-isready','-U','auth']
      interval: 30s
      timeout: 30s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure 
    environment:
      PGADMIN_DEFAULT_EMAIL: ismailkhandokar0@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
      - '5051:443'

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'  #smtp port
      - '8025:8025'  #http port
    volumes:
      - mailhog:/var/lib/mailhog

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis-stack:/var/lib/redis-stack
    environment:
      - REDIS_ARGS=-save 900 1  #poti 900 second er por 1 ta update hbe



volumes:
  postgres:
  mailhog:
  redis-stack: